language: objective-c
osx_image: xcode10.2
branches:
  only:
  - master
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator12.2
  - SCHEME_IOS="TableKit"
  - PROJECT_FRAMEWORK="TableKit.xcodeproj"

  matrix:
  - DESTINATION="OS=10.0,name=iPhone 5"          SCHEME="$SCHEME_IOS"     SDK="$IOS_SDK"
  - DESTINATION="OS=11.0,name=iPhone 6"          SCHEME="$SCHEME_IOS"     SDK="$IOS_SDK"
  - DESTINATION="OS=12.0,name=iPhone 7 Plus"     SCHEME="$SCHEME_IOS"     SDK="$IOS_SDK"

script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -project "$PROJECT_FRAMEWORK" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO test